### ISSUE TITLE
Comparação de CRC inválida.

### ISSUE THREAD

**Issue by alfnori** [rprata/pixcode#3]
Quando o código CRC do EMV possui zeros à esquerda a comparação falha.
Acredito que um padLeft do CRC gerado para o tamanho necessário deva resolver. Segue um exemplo de EMV com erro:

![image](https://user-images.githubusercontent.com/22298608/134983290-97451f47-e958-4a3a-8663-50c349a801a6.png)

**Comment by alfnori** [comment]
> Quando o código CRC do EMV possui zeros à esquerda a comparação falha.
> Acredito que um padLeft do CRC gerado para o tamanho necessário deva resolver. Segue um exemplo de EMV com erro:
> 
> ![image](https://user-images.githubusercontent.com/22298608/134983290-97451f47-e958-4a3a-8663-50c349a801a6.png)

```javascript
if (computed_crc.padStart(result.crc.length, '0') !== result.crc.value) {
     throw new Error('Invalid CRC');
}
```

**Comment by rprata** [comment]
Cara, não quer abrir um PR com um teste referente à isso e o fix?

**Comment by rprata** [comment]
Resolvido no [https://github.com/rprata/pixcode/pull/6](https://github.com/rprata/pixcode/pull/6)
